import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../core/theme/app_theme.dart';
import '../../core/constants/app_strings.dart';
import '../../services/notice_service.dart';
import '../../services/storage_service.dart';
import '../../services/auth_service.dart';
import '../../models/notice_model.dart';

class CreateNoticeScreen extends StatefulWidget {
  final NoticeModel? notice; // For editing

  const CreateNoticeScreen({super.key, this.notice});

  @override
  State<CreateNoticeScreen> createState() => _CreateNoticeScreenState();
}

class _CreateNoticeScreenState extends State<CreateNoticeScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final NoticeService _noticeService = NoticeService();
  final AuthService _authService = AuthService();

  String _selectedCategory = 'General';
  bool _isLoading = false;
  String? _uploadStatus;

  // Image attachment
  String? _imagePath;
  String? _imageError;
  Uint8List? _imageBytes;

  // Categories are sourced from the shared AppStrings constant so they stay
  // consistent across the entire system (including the super admin managed list).
  final List<String> _categories = List.from(AppStrings.categories);

  @override
  void initState() {
    super.initState();
    if (widget.notice != null) {
      _titleController.text = widget.notice!.title;
      _descriptionController.text = widget.notice!.description;
      _selectedCategory = widget.notice!.category;
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final storage = StorageService();
    final pickedFile = await storage.pickImage();

    if (pickedFile == null) return;

    final path = pickedFile.path;
    final extension = StorageService.getExtension(path);

    // Validate image type
    if (!StorageService.isValidImageType(extension)) {
      setState(() {
        _imageError = 'Only JPG, PNG, and WebP images are allowed.';
      });
      return;
    }

    // Read bytes (required for Web where path is a blob URL, also used for size validation)
    final bytes = await storage.readImageBytes(pickedFile);
    if (bytes == null || bytes.isEmpty) {
      setState(() {
        _imageError = 'Could not read the selected image. Please try again.';
      });
      return;
    }

    // Validate image size using bytes
    if (!StorageService.isValidImageSize(bytes.length)) {
      setState(() {
        _imageError = 'Image must be less than 10 MB.';
      });
      return;
    }

    setState(() {
      _imagePath = path;
      _imageBytes = bytes;
      _imageError = null;
    });
  }


  Future<void> _submitNotice() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() {
      _isLoading = true;
      _uploadStatus = 'Creating notice...';
    });

    try {
      final user = _authService.currentUser;
      final userData = await _authService.getUserData(user?.uid ?? '');

      if (user == null || userData == null) {
        _showError('Please login to create notices');
        return;
      }

      final now = DateTime.now();
      final noticeId = widget.notice?.id ?? '';

      final notice = NoticeModel(
        id: noticeId,
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim(),
        category: _selectedCategory,
        authorId: user.uid,
        authorName: userData.name,
        createdAt: widget.notice?.createdAt ?? now,
        status: NoticeStatus.pending,
        likesCount: widget.notice?.likesCount ?? 0,
      );

      if (widget.notice != null) {
        // Update existing notice - preserve existing image data
        setState(() => _uploadStatus = 'Updating notice...');
        final updatedNotice = notice.copyWith(
          imageUrl: widget.notice!.imageUrl,
        );
        await _noticeService.updateNotice(
          notice: updatedNotice,
          imagePath: _imagePath,
          imageBytes: _imageBytes?.toList(),
          // Only remove existing image if user explicitly replaces with new one
          removeImage: false,
        );
        _showSuccess('Notice updated successfully');
      } else {
        // Create new notice with ID generated by Firestore
        setState(() => _uploadStatus = 'Uploading image...');
        final docRef = notice.id.isEmpty
            ? notice.copyWith(
                id: FirebaseFirestore.instance
                    .collection('notices')
                    .doc()
                    .id,
              )
            : notice;

        await _noticeService.createNotice(
          notice: docRef,
          imagePath: _imagePath,
          imageBytes: _imageBytes?.toList(),
        );
        _showSuccess('Notice submitted for approval');
      }

      if (!mounted) return;
      Navigator.pop(context);
    } catch (e) {
      _showError(e.toString());
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
          _uploadStatus = null;
        });
      }
    }
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: AppTheme.secondaryColor,
      ),
    );
  }

  void _showSuccess(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message), backgroundColor: Colors.green),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.notice != null ? 'Edit Notice' : 'Create Notice'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Title
              TextFormField(
                controller: _titleController,
                textCapitalization: TextCapitalization.words,
                decoration: const InputDecoration(
                  labelText: AppStrings.noticeTitle,
                  hintText: 'Enter notice title',
                  prefixIcon: Icon(Icons.title),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return AppStrings.fieldRequired;
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Category
              DropdownButtonFormField<String>(
                initialValue: _selectedCategory,
                decoration: const InputDecoration(
                  labelText: AppStrings.noticeCategory,
                  prefixIcon: Icon(Icons.category),
                ),
                items: _categories.map((category) {
                  return DropdownMenuItem(
                    value: category,
                    child: Text(category),
                  );
                }).toList(),
                onChanged: (value) {
                  setState(() => _selectedCategory = value!);
                },
              ),
              const SizedBox(height: 16),

              // Description
              TextFormField(
                controller: _descriptionController,
                maxLines: 8,
                textCapitalization: TextCapitalization.sentences,
                decoration: const InputDecoration(
                  labelText: AppStrings.noticeDescription,
                  hintText: 'Enter notice description',
                  alignLabelWithHint: true,
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return AppStrings.fieldRequired;
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),

              // --- Image Section (Optional) ---
              const Text(
                'Image (Optional)',
                style: TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 12),

              // Image Attachment
              _buildImagePicker(),
              const SizedBox(height: 24),

              // Upload Progress Indicator
              if (_isLoading && _uploadStatus != null)
                Padding(
                  padding: const EdgeInsets.only(bottom: 16),
                  child: Row(
                    children: [
                      const SizedBox(
                        width: 20,
                        height: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      ),
                      const SizedBox(width: 12),
                      Text(
                        _uploadStatus!,
                        style: TextStyle(color: Colors.grey.shade600),
                      ),
                    ],
                  ),
                ),


              // Submit Button
              ElevatedButton(
                onPressed: _isLoading ? null : _submitNotice,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                ),
                child: _isLoading
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          valueColor: AlwaysStoppedAnimation(Colors.white),
                        ),
                      )
                    : Text(
                        widget.notice != null
                            ? AppStrings.update
                            : AppStrings.submit,
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildImagePicker() {
    return Container(
      decoration: BoxDecoration(
        border: Border.all(
          color: _imageError != null ? Colors.red : Colors.grey.shade300,
        ),
        borderRadius: BorderRadius.circular(12),
      ),
      padding: const EdgeInsets.all(12),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.image, color: AppTheme.primaryColor),
              const SizedBox(width: 8),
              const Text(
                'Attach Image',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500),
              ),
              const Spacer(),
              if (_imagePath != null)
                IconButton(
                  icon: const Icon(Icons.close, size: 20, color: Colors.red),
                  onPressed: () {
                    setState(() {
                      _imagePath = null;
                      _imageBytes = null;
                      _imageError = null;
                    });
                  },
                  tooltip: 'Remove image',
                ),
            ],
          ),
          if (_imagePath != null) ...[
            const SizedBox(height: 8),
            // Image Preview Section
            Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: Colors.grey.shade200),
              ),
              padding: const EdgeInsets.all(4),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(6),
                child: Image.file(
                  File(_imagePath!),
                  height: 180,
                  width: double.infinity,
                  fit: BoxFit.contain,
                  errorBuilder: (_, _, _) => Container(
                    height: 80,
                    color: Colors.grey.shade100,
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(Icons.broken_image,
                            color: Colors.grey.shade400, size: 32),
                        const SizedBox(width: 8),
                        Text(
                          'Preview not available',
                          style: TextStyle(
                              color: Colors.grey.shade500, fontSize: 13),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 8),
            // File info row
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
              decoration: BoxDecoration(
                color: Colors.grey.shade50,
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: Colors.grey.shade200),
              ),
              child: Row(
                children: [
                  const Icon(Icons.image_outlined,
                      color: AppTheme.primaryColor, size: 18),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      StorageService.getFileName(_imagePath!),
                      style: const TextStyle(fontSize: 13),
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                  const Icon(Icons.check_circle,
                      color: Colors.green, size: 18),
                ],
              ),
            ),
          ] else ...[
            const SizedBox(height: 8),
            SizedBox(
              width: double.infinity,
              child: OutlinedButton.icon(
                onPressed: _isLoading ? null : _pickImage,
                icon: const Icon(Icons.add_photo_alternate, size: 20),
                label: const Text('Choose Image (JPG, PNG, WebP)'),
              ),
            ),
          ],
          if (_imageError != null)
            Padding(
              padding: const EdgeInsets.only(top: 4),
              child: Text(
                _imageError!,
                style: const TextStyle(color: Colors.red, fontSize: 12),
              ),
            ),
        ],
      ),
    );
  }
}